export const programmingLanguages = [
    {label: 'C++'},
    {label: 'Java'},
    {label: 'Python'},
    {label: 'C'},
    {label: 'C#'},
    {label: 'JavaScript'},
    {label: 'Ruby'},
    {label: 'Kotlin'},
    {label: 'Scala'},
    {label: 'Swift'},
    {label: 'Rust'},
    {label: 'Go'},
    {label: 'Haskell'},
    {label: 'PHP'},
    {label: 'Perl'},
    {label: 'Pascal'},
    {label: 'Lua'},
    {label: 'R'},
    {label: 'Dart'},
    {label: 'TypeScript'},
    {label: 'Fortran'},
] 